---
kind: Service
apiVersion: v1
metadata:
  name: todos
  namespace: default
spec:
  selector:
    app: todos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  externalIPs:
    - 192.168.64.4
  type: LoadBalancer
